repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: local
    hooks:

    # See pyproject.toml for black configuration
    - id: black
      name: black
      entry: black
      language: system
      # files: ^tests,^systech_account,^utils,^yahshua_api
      types: [python]

    # See setup.cfg for flake8 configuration
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        # files: ^tests,^systech_account,^utils,^yahshua_api
        # files: ^systech_account,^tests,
        types: [python]

    # See setup.cfg for pycodestyle configuration
    -   id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: system
        # files: ^tests,^systech_account,^utils,^yahshua_api
        types: [python]

    # See setup.cfg for isort configuration
    -   id: isort
        name: isort
        entry: isort
        language: system
        # files: ^tests,^systech_account,^utils,^yahshua_api
        types: [python]
