# Generated by Django 4.0.4 on 2022-05-26 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark_folder',
            unique_together={('user', 'name')},
        ),
    ]
