# Generated by Django 4.0.4 on 2022-05-26 09:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bookmark_folder_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='display_title',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
